<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_entity_info_alter().
 */
function apps_entity_restrictions_reports_entity_info_alter(&$entity_info) {
  $entity_info['entity_view_count']['bundle admin ui'] = array(
    'path' => 'admin/structure/entity_view_count',
    'permission' => 'manage entity view count fields',
  );
}

/**
 * Implements hook_permission().
 */
function apps_entity_restrictions_reports_permission() {
  return array(
    'manage entity view count fields' => array(
      'title' => t('Manage entity view count fields'),
      'description' => t('Grant this permission to users which can manage entity view count fields.'),
    ),
  );
}

/**
 * Implements hook_entity_bundle_ENTITY_TYPE_bundle_info().
 */
function apps_entity_restrictions_reports_entity_bundle_entity_view_count_bundle_info() {
  return array(
    'apps_usage' => array(
      'label' => t('Apps usage'),
      'description' => t('Track usages for apps requests.'),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function apps_entity_restrictions_reports_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_apps_entity_restriction_app_event_listener().
 */
function apps_entity_restrictions_reports_apps_entity_restriction_app_event_listener(AppsEntityRestriction $app, $info) {
  $parameters = array(
    '@method' => $info['method'],
    '@entity_type' => $info['entity_type'],
    '@entity_id' => $info['entity_id'],
  );

  $evc = entity_view_count_create(array());
  $evc->entity_id = $app->getId();
  $evc->entity_type = 'apps_entity_restrictions';
  $evc->type = 'apps_usage';

  $wrapper = entity_metadata_wrapper('entity_view_count', $evc);

  $logs = array(
    'property_operation_not_allowed' => array(
      'general' => 'The app made a bad @method request against @property for @entity_type.',
      'object' => 'The app made a bad @method request against @property for @entity_type:@entity_id.',
    ),
    'general_operation_not_allowed' => array(
      'general' => 'The app made a bad @method request against a @entity_type endpoint.',
      'object' => 'The app made a bad @method request against @entity_type:@entity_id.',
    ),
    'general_operation_allowed' => array(
      'general' => 'The app made a good @method request against a @entity_type.',
      'object' => 'The app made a good @method request against @entity_type:@entity_id.',
    ),
  );

  if ($info['reason'] == 'property_operation_not_allowed') {
    $parameters['@property'] = $info['property'];
  }

  $log_message = empty($info['entity_id']) ? $logs[$info['reason']]['general'] : $logs[$info['reason']]['object'];
  $status = $info['reason'] == 'general_operation_allowed' ? 'Passed' : 'Failed';

  $wrapper->field_request_status->set($status);
  $wrapper->field_info->set(format_string($log_message, $parameters));
  $wrapper->save();
}
