<?php

/**
 * @file
 * apps_entity_restrictions_test.module
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function apps_entity_restrictions_test_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function apps_entity_restrictions_test_entity_info_alter(&$info) {
  // todo: add a variable to decide when to allow the alteration and when not.
  // We need an entity without any access callback.
  $info['entity_test']['access callback'] = '';

  // We need an entity with access callback.
  $info['entity_test2']['access callback'] = 'apps_entity_restrictions_test_entity_access_callback';
}

/**
 * Access callback. Dummy access callback.
 */
function apps_entity_restrictions_test_entity_access_callback() {
  return TRUE;
}
